environ:
  seed: 42
  device: "cuda"
  output_dir: "./outputs/crowdsam_vis"
data:
  dataset: "crowdhuman"
  dataset_root: "./dataset/crowdhuman"
  json_file: "./dataset/crowdhuman/val_visible.json"
  train_file: "./dataset/crowdhuman/train_crowdhuman_10shot.json"
  odgt_file: "./dataset/crowdhuman/annotation_val.odgt"
model:
  dino_repo: "./dinov2"
  dino_checkpoint: "./weights/dinov2_vitl14_pretrain.pth"
  dino_model: "dinov2_vitl14"
  sam_checkpoint: "./weights/sam_vit_l_0b3195.pth"
  sam_model: "vit_l"
  sam_arch: "crowdsam"
  sam_adapter_checkpoint: "./adapter_weights/10_shot.pth"
  n_class: 1
  max_size: 1024
  trainfree: False
train:
  default: 0
  n_shot: 10
  seed: 1
  samples_per_batch: 30
  neg_factor: 1
  steps: 2000
  lr: 0.00001
  optimizer: "adamw"
  weight_decay: 0.0001
  save_path: "adapter_weights/10_shot.pth"
test:
  output_rles: False
  #cropping 
  crop_n_layers: 0
  crop_nms_thresh: 0.7
  crop_overlap_ratio: 0.341 #512/1500

  #forward options
  pos_sim_thresh: 0.5
  apply_box_offsets: False
  grid_size: 192

  #eps
  max_prompts: 500
  filter_thresh: 0.7
  points_per_batch: 32
  mask_selection: "max_iou"
  max_size: 1024

  #post processing
  fuse_simmap: False
  min_mask_region_area: 100
  box_nms_thresh: 0.65
  stability_score_thresh: 0.8
  stability_score_offset: 1
  pred_iou_thresh: 0.1

vis:
  vis_thresh: 0.6

